### ISSUE TITLE
Error Qt_5.10' not found

### ISSUE THREAD

**Issue by hwp9527** [carloscn/tinyserial#4]
tinyserial: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by tinyserial)
I had used the cmd "sudo apt install -f", and found out the qt had installed yet.

**Comment by carloscn** [comment]
Hello, Have you ever installed QtCreator IDE on your pc ? The error prompt information your mentioned display that some Qt libs don't included in your pc. I suggest you to do the cmd : 

sudo apt-get install qt5-default qttools5-dev-tools

on your ubuntu system.

**Comment by carloscn** [comment]
Hello, Have you ever installed QtCreator IDE on your pc ? The error prompt information your mentioned display that some Qt libs don't be included in your pc. I suggest you to do the cmd :

**Comment by carloscn** [comment]
Hello, Have you ever installed QtCreator IDE on your pc ? The error prompt information your mentioned display that some Qt libs don't be included in your pc. I suggest you to do the cmd :

sudo apt-add-repository ppa:canonical-qt5-edgers/ubuntu1204-qt5
sudo apt-get update
sudo apt-get install qt5-default

on your ubuntu cmd.

**Comment by plumewind** [comment]
hello,

it still appear this problem:
tinyserial: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by tinyserial)

**Comment by carloscn** [comment]
fixed it on https://github.com/carloscn/tinyserial/releases/tag/1.2.0  
Please download the lastest version.
I closed the issue. if have any question, please pull a new issue on the list. thanks very much.

**Comment by zhouchuanfu** [comment]
Hello, I download 1.2.0-1 version, but still show :
tinyserial: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by tinyserial)

**Comment by carloscn** [comment]
> Hello, I download 1.2.0-1 version, but still show :
> tinyserial: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by tinyserial)

I have reopen this issue. Check it later.

**Comment by zhiyingtian** [comment]
> Hello, I download 1.2.0-1 version, but still show :
> tinyserial: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by tinyserial)

Check to see if the file exists and the environment variable.

![image](https://user-images.githubusercontent.com/16663007/108615396-9d40dc00-743e-11eb-9346-dded7149e5a6.png)

**Comment by carloscn** [comment]
> > Hello, I download 1.2.0-1 version, but still show :
> > tinyserial: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by tinyserial)
> 
> Check to see if the file exists and the environment variable.
> 
> ![image](https://user-images.githubusercontent.com/16663007/108615396-9d40dc00-743e-11eb-9346-dded7149e5a6.png)

@zhouchuanfu  Hi please check the enviroenment variable on your linux host.

**Comment by zhouchuanfu** [comment]
![图片](https://user-images.githubusercontent.com/46174387/108848589-219c8600-761c-11eb-9e0c-0c907fd499d5.png)
Hello,this is my environment variable.

**Comment by wifialan** [comment]
Add the path “/usr/lib/x86_64-linux-gnu” to the environment variable. See if the software works properly.

**Comment by zhiyingtian** [comment]
> ![图片](https://user-images.githubusercontent.com/46174387/108848589-219c8600-761c-11eb-9e0c-0c907fd499d5.png)
> Hello,this is my environment variable.

Add the path “/usr/lib/x86_64-linux-gnu” to the environment variable. See if the software works properly.

**Comment by zhouchuanfu** [comment]
![图片](https://user-images.githubusercontent.com/46174387/108978194-5237fa80-76c4-11eb-8528-a09e19f75bff.png)
Hello,the problem is still.

**Comment by zhiyingtian** [comment]
> ![图片](https://user-images.githubusercontent.com/46174387/108978194-5237fa80-76c4-11eb-8528-a09e19f75bff.png)
> Hello,the problem is still.

Please use the "ldd" command to check the file path pointed by "libQt5Core.so.5" .

![image](https://user-images.githubusercontent.com/16663007/108983477-dfca1900-76c9-11eb-9d4b-12f4644c082a.png)

**Comment by zhouchuanfu** [comment]
![图片](https://user-images.githubusercontent.com/46174387/109009287-532f5300-76e9-11eb-9253-113da4abf389.png)

**Comment by carloscn** [comment]
Hi @zhouchuanfu ,

Your host qt-base version(qt 5.9.5) is lower than the verion of qt 5.10.0 that is we development base version. Upgrading your qt-base version on your linux host can help you solve the problem. I recommond a method to sovle this problem. You can follow it, but notice that if you upgrade your global qt-base version on your linux host that maybe invoke some problems into other qtbase APPs. Please pay attention to risk assessment.

On the Ubuntu 20.04, update the qt-base version from qt5.9.5 to qt5.12.9: 

`sudo add-apt-repository ppa:beineri/opt-qt-5.12.9-focal`
`sudo apt update`
`sudo apt install qt512-meta-full`

For system wide usage, create default.conf file at /usr/lib/x86_64-linux-gnu/qtchooser with following content:
```
/opt/qt512/bin
/opt/qt512/lib
```
That's it, it should be updated by now. qmake -v outputs the current Qt and qmake version.

*Reference ubuntu Qt app centor: https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.12.9-focal*

**Comment by zhouchuanfu** [comment]
Hi, @carloscn thank you details for reply, but I can not change, because I have other application based on qt. 
Sorry.

**Comment by hanzheteng** [comment]
I encountered the same issue under Ubuntu 18 when running the latest v1.2.0 release. 
```
tinyserial: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by tinyserial)
```

**Comment by carloscn** [comment]
> I encountered the same issue under Ubuntu 18 when running the latest v1.2.0 release.
> 
> ```
> tinyserial: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by tinyserial)
> ```

You can download the ubuntu 18.04 release by:
https://github.com/carloscn/tinyserial/releases/download/v1.4/TinySerial-v1.4.0-ubuntu18.04-amd64.deb

**Comment by carloscn** [comment]
Fixed on release v1.4
